#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

YELLOW_COLOR="\u001b[33m"
GREEN_COLOR="\033[0;32m"
RESET_COLOR="\u001b[39m"

printf "${YELLOW_COLOR}⚠ Checking for errors...${RESET_COLOR}\n"
yarn cleanup
yarn lint:fix
printf "${GREEN_COLOR}✓ No errors found. Committing your changes!${RESET_COLOR}\n"